### ISSUE TITLE
Please use provided blog title in more places

### ISSUE THREAD

**Issue by yasmoradi** [msynk/bLOG2#2]
I've provided a blog title in web.config
I'd like to use that blog title in following places:
1- RssHandler.cs for Rss title
2- < h1 class="blog-title">< a href="/">bLOG2</ a></ h1> >> Use blog title instead of bLOG2
3- < section class="copyright">All content copyright >> Use blog title for Copyright owner
Thanks in advance

**Comment by msynk** [comment]
Thank you for your suggestion. I've added & pushed required changes.

**Comment by yasmoradi** [comment]
Thanks. It worked in RssHandler.cs, but Layout.html has some troubles.

**Comment by msynk** [comment]
Thanks again. i fixed that issue too.
